#Robot Frames (CHECK URDF)
base_link: "base_link"
lfoot: "l_ankle"
rfoot: "r_ankle"
modelname: "/home/master/dp_ws/src/serow/share/urdf/cogimon.urdf"
#ROS Topic Names
lleg_imu_topic: "/imu_L_data"
rleg_imu_topic: "/imu_R_data"
#imu_topic: "/imu/data"
imu_topic: "/xbotcore/cogimon/imu/imu_link"
joint_state_topic: "/cogimon/joint_states"
lfoot_force_torque_topic: "/xbotcore/cogimon/ft/l_leg_ft"
rfoot_force_torque_topic: "/xbotcore/cogimon/ft/r_leg_ft"
#TF from IMU to Base 
#For imu0 (external IMU)
#TF from IMU to Body
T_B_I: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 , 1, 0, 0, 0 ,0, 1]
#For left leg imu
#T_L_I: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 ,1 ,0, 0, 0, 0 , 1]
T_L_I: [ 0.9823,   -0.0582,    0.1780, 0, 0.1804,    0.0390,   -0.9828, 0,  0.0503,    0.9975,    0.0488, 0, 0,0,0,1]

#For right leg imu
#T_R_I: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 ,1 ,0, 0, 0, 0 , 1]
T_R_I: [0.9841,   -0.0713,    0.1627, 0, 0.1674,    0.0655,   -0.9837,  0, 0.0595,    0.9953,    0.0764,  0, 0, 0, 0, 1]
#TF from F/T to Left Foot
T_FT_LL: [-1, 0, 0, 0, 0, -1, 0, 0, 0, 0 , -1 , -0.035, 0, 0, 0, 1]
#TF from F/T to Right Foot
T_FT_RL: [-1, 0, 0, 0, 0, -1, 0, 0, 0, 0 , -1 , -0.035, 0, 0, 0, 1]
#ROS Topic Frequencies in Hz
leg_imu_topic_freq: 100
imu_topic_freq: 200
joint_topic_freq: 200
fsr_topic_freq: 200  

#Compute Joint Velocities
joint_cutoff_freq: 16
joint_noise_density: 0.17  # rad

#Mahony Filter for attitude
useMahony: true
Mahony_Kp_base_imu: 0.001
Mahony_Ki_base_imu: 0.0
Mahony_Kp_lleg_imu: 0.001
Mahony_Ki_lleg_imu: 0.0
Mahony_Kp_rleg_imu: 0.001
Mahony_Ki_rleg_imu: 0.0
#Madgwick Filter for attitude if useMahony is false
Madgwick_gain_base_imu: 0.0003
Madgwick_gain_lleg_imu: 0.0003
Madgwick_gain_rleg_imu: 0.0003
#Filter Params
gravity: 9.80 #gravity constant (m/s^2)
maxImuCalibrationCycles: 100
maxAttitudeEstimationConvergeCycles: 100
#Gyro LPF
useGyroLPF: false
#Cutt-off Frequencies
gyro_cut_off_freq: 6.0  #Only if useGyroLPF is true
#Gyro Moving Average Filter
maWindow: 14 #buffer size, the larger the smoother and delayed the signal, only if useGyroLPF is false
