#Robot Frames (CHECK URDF)
base_link: "base_link"
lfoot: "left_sole_link"
rfoot: "right_sole_link"
modelname: "/home/master/talos_walk_ws/src/whole_body_ik/share/urdf/talos_full_v2.urdf"
#ROS Topic Names
lleg_imu_topic: "/left_leg_imu"
rleg_imu_topic: "/imu/data"
imu_topic: "/base_imu"
himu_topic: "/camera/imu"
joint_state_topic: "/joint_torque_states"
lfoot_force_torque_topic: "/left_ankle_ft"
rfoot_force_torque_topic: "/right_ankle_ft"
ground_truth_gait_phase_topic: "/ground_truth/gait_phase"
#TF from IMU to Base 
T_B_I: [0, 1, 0, 0, 1, 0, 0, 0, 0, 0 , -1, 0, 0, 0 ,0, 1]
#For left leg imu
#T_L_I: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 , 1 , 0, 0, 0 ,0, 1] 
T_L_I: [0.9974,    0.0658 ,  -0.0295, 0,0.0365 ,  -0.1085,    0.9934, 0, 0.0621,   -0.9919 ,  -0.1106, 0, 0, 0, 0, 1]

#For right leg imu
#T_R_I: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 , 1 , 0, 0, 0 ,0, 1] 
T_R_I: [0.9884,   -0.1510 ,   0.0140, 0,  0.0331,    0.1244 ,  -0.9917, 0, 0.1480,    0.9807,    0.1280, 0, 0,  0, 0,1]
#TF from F/T to Left Foot
T_FT_LL: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 , 1 , 0, 0, 0 ,0, 1]
#TF from F/T to Right Foot
T_FT_RL: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0 , 1 , 0, 0, 0 ,0, 1]
#ROS Topic Frequencies in Hz
imu_topic_freq: 25
leg_imu_topic_freq: 25
fsr_topic_freq: 25
joint_topic_freq: 25
#Steady State Joint Kalman Filter (KF)
computeJointVelocity: false
joint_cutoff_freq: 12
joint_noise_density: 0.5
#Mahony Filter for attitude
useHeadIMU: false
useHeadOrientation: false
useBaseOrientation: false
useLLegOrientation: false
useRLegOrientation: false
useMahony: true
Mahony_Kp_base_imu: 2.5
Mahony_Ki_base_imu: 0.0
Mahony_Kp_head_imu: 3.5
Mahony_Ki_head_imu: 0.0
Mahony_Kp_lleg_imu: 2.5
Mahony_Ki_lleg_imu: 0.0
Mahony_Kp_rleg_imu: 2.0
Mahony_Ki_rleg_imu: 0.0
#Madgwick Filter for attitude if useMahony is false
Madgwick_gain_base_imu: 0.3
Madgwick_gain_lleg_imu: 0.3
Madgwick_gain_rleg_imu: 0.3
Madgwick_gain_head_imu: 0.3
#Filter Params
gravity: 9.81 #gravity constant (m/s^2)
maxImuCalibrationCycles: 50
maxAttitudeEstimationConvergeCycles: 100
#Gyro LPF
useGyroLPF: true
#Cutt-off Frequencies
gyro_cut_off_freq: 15.0  #Only if useGyroLPF is true
#Gyro Moving Average Filter
maWindow: 14 #buffer size, the larger the smoother and delayed the signal, only if useGyroLPF is false